server:
  # 端口
  port: 8086
spring:

  # 邮件配置
  mail:
    # 邮件服务器地址
    host: smtp.qq.com
    # 协议
    protocol: smtp
    # 编码格式
    default-encoding: utf-8
    # 授权码（在邮箱开通服务时获取）
    password: zwgskpxtxsrhbeie
    # 发送者邮箱地址
    username: 1871701414@qq.com
    # 端口（不同邮箱端口号不同）
    port: 25



  # rabbitmq配置
  rabbitmq:
    # 用户名
    username: guest
    # 密码
    password: guest
    # 服务器地址
    host: 127.0.0.1
    # 端口
    port: 5672
    listener:
      simple:
        #开启手动确认
        acknowledge-mode: manual

  redis:
    timeout: 10000ms
    host: 116.62.6.60
    port: 6379
    database: 0
    password: 990915
    lettuce:
      pool:
        max-active: 1024
        max-wait: 10000ms
        max-idle: 200
        min-idle: 5
